icalcomponent_get_duration() — calculate the duration differently for VEVENT and VTODO
libical/libical pull request #534
Opened 2022-01-04 15:17 UTC by dilyanpalauzov

For VEVENT and VAVAILABILITY calculate the distance between DTSTART and DTEND.

For VTODO calculate the distance between DTSTART and DUE.

2022-01-05 21:34 UTC, winterz commented
@dilyanpalauzov could you also add a blurb to the top-level ReleaseNotes.txt about this change?  Maybe add a test to regression.c too

@mcrha to double-check: you are ok with this patch now?

2022-01-05 21:38 UTC, winterz commented
nit: 2 lines in your patch are longer than 100 chars.  would be appreciated if you'd split those over more than 1 line.

2022-01-06 08:29 UTC, mcrha commented
> @mcrha to double-check: you are ok with this patch now?

Yes, I am. It makes the evolution-data-server tests pass without additional changes (but I'll keep the changes there, because they make sense).

2022-01-07 18:20 UTC, ksmurchison requested changes
The logic looks good to me, but I have a couple of comments inline.

2022-01-07 18:20 UTC, ksmurchison commented on src/libical/icalcomponent.c
> +    if (kind != ICAL_VEVENT_COMPONENT && kind != ICAL_VAVAILABILITY_COMPONENT
I think a switch() statement would be cleaner (and more extendible) than an if.  I need to tweak the VPOLL support to match the current IETF draft, and will have to add it in here eventually.

2022-01-07 18:20 UTC, ksmurchison commented on src/libical/icalcomponent.c
> +        struct icaltimetype end = kind == ICAL_VTODO_COMPONENT
Can't we grab the end time in the new switch statement above?

2022-01-09 09:36 UTC, dilyanpalauzov commented
I have added text to ReleaseNotes.txt, added tests to regression.c, switched to `switch()`, extended the documentation of `icalcomponent_get_duration()` and `icaltimetype icalcomponent_get_dtend()` about the implicit calculations for VEVENT.

2022-01-10 08:25 UTC, dilyanpalauzov commented
I added handling for the AVAILABILITY component, apart from VTODO, VEVENT, VFREEBUSY and VAVAILABILITY components.

2022-01-10 08:32 UTC, dilyanpalauzov commented
I wrote `AVAILABILITY`, but I meant `AVAILABLE`.

2022-01-13 12:05 UTC, winterz commented
I think we need this in the 3.0 branch as well.  The patch doesn't apply cleanly to 3.0, but I can cherry-pick and fix it, hopefully.
Any other final comments @ksmurchison or @mcrha ?

2022-01-13 12:09 UTC, ksmurchison approved these changes

2022-01-13 12:09 UTC, ksmurchison approved these changes
LGTM

2022-01-13 12:30 UTC, winterz reviewed
fixes needed for old C compilers

2022-01-13 12:30 UTC, winterz commented on src/libical/icalcomponent.c
>      icalproperty *end_prop = icalcomponent_get_first_property(inner, ICAL_DTEND_PROPERTY);
declare `icalproperty *end_prop, *dur_prop` and `struct icaltimetype ret` above the switch else some older C compilers will barf.

2022-01-13 12:30 UTC, winterz commented on src/libical/icalcomponent.c
>      icalproperty *dur_prop = icalcomponent_get_first_property(inner, ICAL_DURATION_PROPERTY);
same here. `icalproperty *dur_prop` and `struct icaldurationtype ret` must be declared above the switch

2022-01-14 06:16 UTC, dilyanpalauzov commented
I removed the handling of AVAILABLE, and left VAVAILABILITY.   The `icalcomponent_get_duration()` and `icalcomponentget_dtend()` functions get as parameter a VCALENDAR component and act on its first child component. AVAILABLE is not direct child of VCALENDAR.

2022-01-14 07:34 UTC, mcrha commented
> functions get as parameter a VCALENDAR component and act on its first child component. AVAILABLE is not direct child of VCALENDAR.

Passing a VCALENDAR component feels like a misuse of the function. You should not expect anything about the caller's intention when he/she does so. The first child component can be a VTIMEZONE or any other. I mean, I would not use the first child, when the passed in component is not one of the expected component types, just return a null-time.

2022-01-14 07:46 UTC, dilyanpalauzov commented
I was wrong: `icalcomponent_get_duration()` and `icalcomponet_get_dtent()` call `icalcomponent_get_inner()`.  For VCALENDAR `icalcomponent_get_inner()` returns the first child, otherwise it returns the passed parameter.

I have restored the handling of the AVAILABLE component.

2022-01-14 07:49 UTC, dilyanpalauzov commented
Removing `icalcomponent *inner = icalcomponent_get_inner(comp);` from `icalcomponent_get_dtend()` and others shall be handled in a different ticket.

2022-01-14 09:42 UTC, mcrha commented
> Removing `icalcomponent *inner = icalcomponent_get_inner(comp);` from `icalcomponent_get_dtend()` and others shall be handled in a different ticket.

I agree. I understood from your previous comment that you added that there. If it was there already, then it can be some library users depend on the current behavior. In that case it's safer to be left there, even I still believe it's a bad idea.

2022-01-15 21:50 UTC, merged

2022-01-15 21:50 UTC, winterz commented
I'll work on cherry-picking this back to the 3.0 branch.
unless there are objections?

2022-01-17 09:45 UTC, mcrha commented
No objection from my side. The evolution-data-server unit tests pass with it with no problem (the apply of the patch reports a lot of offset-s, but otherwise applies the code changes cleanly).